
title: Configuration
type: object
properties: 
    host: 
        type: string
        default : localhost
        description: The hostname to bind the server to
    port: 
        type: integer
        default : 8080
        minimum: 1
        maximum: 65535
        description: The port to bind the server to   
    username: 
        type: string
        default : someuser
        description: The username used during login authentication
    password: 
        type: string
        default : somepass
        description: The password used during login authentication
    routers: 
        type: array
        items: 
            type: object
            properties: 
                name: 
                    type: string
                    default: router01.pop01
                    description: User friendly name of the router
                address: 
                    type: string
                    default: 192.0.2.1
                    description: Hostname or IP address of the router
                vrfs:
                    type: array
                    items: 
                        type: object
                        properties: 
                            name: 
                                type: string
                                default: global
                                description: Name of the VRF
                            loopback: 
                                type: string
                                default: Lo0
                                description: Name of the VRF
                        additionalProperties: False
                        required:
                            - name
                            - loopback
                    minItems: 1
                formats: 
                    type: array
                    items: 
                        type: object
                        properties: 
                            format: 
                                type: string
                                default: text/plain
                                description: Internet media type as of RFC6838
                            driver: 
                                type: string
                                default: beagle.drivers.ios
                                description: Driver for the router
                        additionalProperties: False
                        required: 
                            - format
                            - driver
                    minItems: 1
                location: 
                    type: string
                    default: Somewhere on planet earth
                    description: The physical location of the router
                asn: 
                    type: integer
                    default: 64496
                    minimum: 1
                    maximum: 4294967296
                    description: The ASN of the router
            required: 
                - name
                - formats
                - vrfs
                - location
                - asn
            additionalProperties: False
        minItems: 1
    webpage: 
        type: string
        default : html/beagle.html
        description: Path to the Jinja2 template for the web page
    limiter: 
        type: object
        properties: 
            amount: 
                type: integer
                default : 3
                minimum: 0
                description: Amount of requests per user for the\
                 time unit defining the period
            period: 
                type: string
                default : minute
                description: Time unit defining the period
                enum:
                    - second
                    - minute
                    - hour
                    - day
                    - month
                    - year
        required:
            - amount
            - period
        additionalProperties: False
        default: 
            amount: 3
            period: 'minute'
    findreplace: 
        type: array
        items: 
            type: object
            properties: 
                find: 
                    type: string
                    description: |
                        The REGEX to be found.
                        It supports matches for instance:

                            (?P<words>\w+) applied to the string somewords

                        Will return the following mapping that can be used with replace:

                            'words': 'somewords'
                replace:
                    type: string
                    description: |
                        The string to be used as format for the replacement.
                        It can borrow matches from regex for instance:

                            I am replacing %(words) applied to 'words': 'somewords'

                        Will return the following text:

                            I am replacing somewords
            required: 
                - find
                - replace
            additionalProperties: False
        minItems: 0
        default: []
    debug: 
        type: boolean
        description: Turns on flask debugging
        default: False
    runtime: 
        type: object
        properties: 
            min: 
                type: integer
                default: 30
                description: Minimun runtime value the use can set
            max: 
                type: integer
                default: 120
                description: Maximum runtime value the use can set
        required:
            - min
            - max
        additionalProperties: False
required:
    - username
    - password
    - routers
additionalProperties: False
